version: '3.7'

networks:
  ws-notifications-network:
    name: ws-notifications-network
    driver: bridge

services:
  ws-nginx:
    container_name: ws-nginx
    image: ws-nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx/:/etc/nginx/
    ports:
      - 443:443
    networks:
      - ws-notifications-network
    depends_on:
      - ws-server
  ws-server:
    #container_name: ws-server
    image: ws-server
    build:
      context: ./
      dockerfile: Dockerfile.server
    networks:
      - ws-notifications-network
  ws-client:
    #container_name: ws-client
    image: ws-client
    build:
      context: ./
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/usr/src/app
    environment:
      WS_SCHEME: wss
      WS_HOSTNAME: ws-nginx
    networks:
      - ws-notifications-network
    depends_on:
      - ws-nginx

