version: '3.7'

networks:
  notifications-network:
    name: notifications-network
    driver: bridge

services:
  ws-nginx:
    container_name: ws-nginx
    image: ws-nginx
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx/:/etc/nginx/
      - ./sse-client:/usr/share/nginx/html/
      - ./swagger:/var/www/swagger/
    ports:
      - 443:443
    networks:
      - notifications-network
    depends_on:
#      - ws-server
      - sse-server
      - nats
#  ws-server:
#    image: ws-server
#    build:
#      context: ./
#      dockerfile: Dockerfile.server
#    networks:
#      - notifications-network
#  ws-client:
#    image: ws-client
#    build:
#      context: ./
#      dockerfile: Dockerfile.client
#    volumes:
#      - ./client:/usr/src/app
#    environment:
#      WS_SCHEME: wss
#      WS_HOSTNAME: ws-nginx
#    networks:
#      - notifications-network
#    depends_on:
#      - ws-nginx
  sse-server:
    image: sse-server
    build:
      context: ./
      dockerfile: Dockerfile.sse.server
    environment:
      NATS_URL: nats
    networks:
      - notifications-network
    depends_on:
      - nats
  nats:
    container_name: nats # Брокер сообщений NATS JetStream
    image: nats:2.12.4
    command: "-js -m 8222" # Включаем JetStream и мониторинг
    ports:
      - "4222:4222" # Клиентский порт
      - "8222:8222" # HTTP мониторинг
    networks:
      - notifications-network

