version: '3.7'

networks:
  dev-network:
    name: dev-network
    driver: bridge

services:
  ws-dev-server:
    container_name: ws-dev-server
    image: golang-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
    ports:
      - 80:80
    networks:
      - dev-network
  ws-dev-client:
    container_name: ws-dev-client
    image: golang-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app
    environment:
      WS_SCHEME: ws
      WS_HOSTNAME: ws-dev-server
    networks:
      - dev-network
  sse-dev-server:
    container_name: sse-dev-server
    image: golang-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./sse-server:/usr/src/app
    ports:
      - 8080:80
    networks:
      - dev-network

