version: '3.7'

networks:
  ws-dev-network:
    name: ws-dev-network
    driver: bridge

services:
  ws-dev-server:
    container_name: ws-dev-server
    image: ws-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app
    ports:
      - 80:80
    networks:
      - ws-dev-network
  ws-dev-client:
    container_name: ws-dev-client
    image: ws-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app
    environment:
      WS_SCHEME: ws
      WS_HOSTNAME: ws-dev-server
    networks:
      - ws-dev-network

