openapi: 3.0.0
info:
  title: Notification Service
  description: Сервис уведомлений
  version: 0.0.0
tags: []
paths:
  /sse-notifications:
    get:
      operationId: Notifications_subscribe
      description: Подключение к потоку SSE уведомлений для конкретного пользователя
      parameters:
        - name: user_id
          in: query
          required: true
          description: Идентификатор пользователя (например, rootcom)
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            text/event-stream:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/ProgressNotification'
                  - $ref: '#/components/schemas/ErrorNotification'
components:
  schemas:
    ErrorNotification:
      type: object
      required:
        - taskId
        - type
        - version
        - timestamp
        - payload
      properties:
        taskId:
          type: string
          description: Уникальный идентификатор задачи
        type:
          type: string
          description: Тип события для маршрутизации на фронтенде
        version:
          type: string
          enum:
            - v1
          description: Версия схемы
        timestamp:
          type: string
          format: date-time
          description: Время создания события (ISO8601)
        payload:
          allOf:
            - $ref: '#/components/schemas/ErrorPayload'
          description: Полезная нагрузка события
      description: Базовая структура уведомления
    ErrorPayload:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
      description: Данные об ошибке
    ProgressNotification:
      type: object
      required:
        - taskId
        - type
        - version
        - timestamp
        - payload
      properties:
        taskId:
          type: string
          description: Уникальный идентификатор задачи
        type:
          type: string
          description: Тип события для маршрутизации на фронтенде
        version:
          type: string
          enum:
            - v1
          description: Версия схемы
        timestamp:
          type: string
          format: date-time
          description: Время создания события (ISO8601)
        payload:
          allOf:
            - $ref: '#/components/schemas/ProgressPayload'
          description: Полезная нагрузка события
      description: Базовая структура уведомления
    ProgressPayload:
      type: object
      required:
        - progress
      properties:
        progress:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
        stepName:
          type: string
      description: Данные о прогрессе выполнения
